repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
        - id: trailing-whitespace
        - id: debug-statements

-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    - id: bandit

-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -   id: black
        language_version: python3.8
        exclude: |
          (?x)(
          migrations |
          manage.py
          )
        ambvrgs: [
          --check,
          --diff,
          --line-length=79,
        ]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        args: [
            --check-only,
            --diff
        ]
