version: '3.7'

services:
    adminer:
        container_name: adminer
        image: adminer
        restart: on-failure
        ports:
            - 8080:8080

    shortener:
        container_name: shortener
        image: shortener:latest
        build:
            context: ./
            dockerfile: .Dockerfile
        env_file:
            - .env
        expose:
            - 5000
        command: >
           bash -c "python manage.py collectstatic --no-input &&
                    python manage.py migrate &&
                    gunicorn wsgi:application  --name shortener --workers 2 --bind=0.0.0.0:5000 --capture-output --access-logfile - -t 300"
        depends_on:
            - "db"
        volumes:
            - ./static_volume:/static

    db:
        container_name: db
        image: postgres:11.5-alpine
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - 5000:80
        volumes:
            - ./static_volume:/static
        depends_on:
            - shortener

volumes:
    postgres_data:
    static_volume: {}
