version: '3.7'

services:
    shortener:
        container_name: shortener
        image: shortener:latest
        build:
            context: ./
            dockerfile: .Dockerfile
        env_file:
            - .env
        expose:
            - 5000
        ports:
            - "5000:5000"
        command: >
           bash -c "python manage.py migrate &&
                    gunicorn wsgi:application  --name shortener --workers 2 --bind=0.0.0.0:5000 --capture-output --access-logfile - -t 300"
        volumes:
            - ./static:/static
volumes:
    static: {}

