# Generated by Django 3.1.7 on 2021-03-05 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2073, validators=[django.core.validators.MaxLengthValidator(2073), django.core.validators.URLValidator()])),
                ('link', models.CharField(blank=True, editable=False, max_length=100)),
            ],
            options={
                'unique_together': {('url', 'link')},
            },
        ),
    ]
