name: Testing
on:
  push:
    branches: [ develop ]

jobs:
  test:
    name: Test Stage
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        echo "${{secrets.DIGITALOCEAN_HOST}}"
      env:
        DIGITALOCEAN_HOST: ${{secrets.DIGITALOCEAN_HOST}}
