name: Testing
on:
  push:
    branches: [ develop ]

jobs:
  test:
    name: Test Stage
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
    steps:
    - shell: bash
      env:
        DIGITALOCEAN_HOST: ${{secrets.DIGITALOCEAN_HOST}}
      run: |
        echo "$$DIGITALOCEAN_HOST"
