name: Testing

on:
  push:
    branches: [ develop ]

jobs:
  test:
    name: Test Stage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Decrypt large secret
      run: ./.github/scripts/decrypt_secret.sh
      env:
        DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        DIGITALOCEAN_KEY: ${{ secrets.DIGITALOCEAN_KEY }}
        DIGITALOCEAN_USER: ${{ secrets.DIGITALOCEAN_USER }}
    - name: Test printing DIGITALOCEAN_HOST
      run: echo $HOME/secrets/dghost.json
    - name: Test printing DIGITALOCEAN_KEY
      run: cat $HOME/secrets/dgkey.json
    - name: Test printing DIGITALOCEAN_USER
      run: echo $DIGITALOCEAN_HOST